# Add additional sync excludes for this repo
exclude package
exclude cmk_addons/plugins/TEMPLATE/**
exclude tests/unit/cmk_addons/plugins/TEMPLATE/
exclude README.md
exclude .devcontainer/template-sync.conf
exclude .devcontainer/symlink.sh