name: Lint

on:
  push:
    paths:
      - '**/*.py'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ruff_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      uses: jpetrucciani/ruff-check@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
